### PR TITLE
Sync new duckdb chapter

### PR DESCRIPTION
**Pull request by VRConservation**
Adding new duckdb chapter for geog-414

### CODE REVIEW

**Comment by giswqs** [comment]
Thank you for your interest in contributing to the repo. I am sorry I won't able to accept this PR. All the notebook cell output should be cleared. CSV files from notebook outputs should not be added. Lab answers should not be added.

**Comment by VRConservation** [comment]
Sorry about this. I think I've misunderstood how to update a cloned repo. I have added the duckdb chapter to my cloned version of geog-414, but still not sure how to easily do it.

**Comment by giswqs** [comment]
You need to to fork my repo to your account, then clone the repo from your account

**Comment by VRConservation** [comment]
Cool. Thanks.

**Pull request closed without merging**
